import { Inter } from 'next/font/google';
import Footer from './components/Layout/Footer';
import NavBar from './components/Layout/NavBar';
import './globals.css';
import ReduxProviders from './Providers/ReduxProviders';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=IM+Fell+French+Canon&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`${inter.className} font-montserrat flex flex-col min-h-screen`}>
        <ReduxProviders>
          <NavBar />
          {children}
          <div className="relative bottom-0">
            <Footer />
          </div>
        </ReduxProviders>
      </body>
    </html>
  );
}
